apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: stackrox-image-scan
spec:
  workspaces:
    - name: roxsecrets
  params:
    - description: |
        Secret containing the address:port tuple for StackRox Central
        (example - rox.stackrox.io:443)
      name: rox_central_endpoint
      type: string
    - description: Secret containing the StackRox API token with CI permissions
      name: rox_api_token
      type: string
    - description: ca of stackrox
      name: rox_ca
      type: string
    - description: |
        Full name of image to scan (example -- gcr.io/rox/sample:5.0-rc1)
      name: image
      type: string
    - default: json
      description: Output format (json | csv)
      name: output_format
      type: string
    - default: 'false'
      description: |
        When set to `"true"`, skip verifying the TLS certs of the Central
        endpoint.  Defaults to `"false"`.
      name: insecure-skip-tls-verify
      type: string
  steps:
    - env:
        - name: ROX_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: rox_api_token
              name: $(params.rox_api_token)
        - name: ROX_CENTRAL_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: rox_central_endpoint
              name: $(params.rox_central_endpoint)
        - name: ROX_CA
          valueFrom:
            secretKeyRef:
              key: rox_ca
              name: $(params.rox_ca)
      image: docker.io/centos@sha256:a1801b843b1bfaf77c501e7a6d3f709401a1e0c83863037fa3aab063a7fdb9dc
      name: rox-image-scan
      script: |
        #!/usr/bin/env bash
        set +x
        export NO_COLOR="True"
        curl -s -k -L -H "Authorization: Bearer $ROX_API_TOKEN" \
          "https://$ROX_CENTRAL_ENDPOINT/api/cli/download/roxctl-linux" \
          --output ./roxctl  > /dev/null; echo "Getting roxctl"
        chmod +x ./roxctl > /dev/null
        ./roxctl image scan \
          $( [ "$(params.insecure-skip-tls-verify)" = "true" ] && \
          echo -n "--insecure-skip-tls-verify") \
          -e "$ROX_CENTRAL_ENDPOINT" --image "$(params.image)" \
          --output "$(params.output_format)" --ca $(workspaces.roxsecrets.path)/rox_ca