---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: upstream-push
  annotations:
    # The event we are targeting as seen from the webhook payload
    # this can be an array too, i.e: [pull_request, push]
    pipelinesascode.tekton.dev/on-event: "push"

    # The branch or tag we are targeting (ie: main, refs/tags/*)
    pipelinesascode.tekton.dev/on-target-branch: "main"

    # Fetch the git-clone task from hub, we are able to reference later on it
    # with taskRef and it will automatically be embedded into our pipeline.
    pipelinesascode.tekton.dev/task: "[golangci-lint, .tekton/tasks/send-slack-notification.yaml, .tekton/tasks/sync-upstream.yaml]"
    # You can add more tasks in here to reuse, browse the one you like from here
    # https://hub.tekton.dev/
    # example:
    # pipelinesascode.tekton.dev/task-2: "[maven, buildah]"

    # How many runs we want to keep attached to this event
    pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  pipelineSpec:
    finally:
      - name: finally
        taskRef:
          name: send-slack-notification
        params:
          - name: report_success
            value: 'true'
          - name: log_url
            value: "https://console-openshift-console.apps.pthangad49f.ocp-gitops-qe.com"         
          - name: openshift
            value: "true"
    workspaces:
      - name: source
      - name: ssh-directory
    tasks:
      # Customize this task if you like, or just do a taskRef
      # to one of the hub task.
      - name: sync-upstream-to-downstream
        taskRef:
          name: sync-upstream
        workspaces:
          - name: source
            workspace: source
          - name: ssh-directory
            workspace: ssh-directory
        params:
          - name: branch
            value: release-next
          - name: upstream
            value: "git@github.com:praveen4g0/upstream.git"
          - name: downstream
            value: "git@gitlab.cee.redhat.com:pthangad/downstream.git"
  workspaces:
  - name: source
    emptyDir: {}
  - name: ssh-directory
    secret:
      secretName: git-credentials
